---
- hosts:  local
  name:   a playbook to configure my work laptop
  connection: local

  roles:
    - firewall
    - myfiles
    - packages
    - libvirtd
    - httpd
    - create-libvirt-network

#- name: Need to configure YubiKey
