---
- hosts:  local
  name:   a playbook to configure my work laptop
  connection: local

  roles:
    - firewall
    - myfiles
    - packages
    - libvirtd
    - httpd
    - openscap
    - create-libvirt-network
    - vpn-profiles

- name: echo YubiKey
  debug: "Need to configure YubiKey"
