---
- name: Enable Google Chrome Repository
  copy:
    src: "../files/google-chrome.repo"
    dest: /etc/yum.repos.d/google-chrome.repo
  become: yes
  tags: packages

- name: Install Atom GPG key
  rpm_key:
    state: present
    key: https://packagecloud.io/AtomEditor/atom/gpgkey
  become: yes
  tags: packages

- name: Enable Atom Repository
  copy:
    src: "../files/atom.repo"
    dest: /etc/yum.repos.d/atom.repo
  become: yes
  tags: packages

- name: Install Packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - libvirt-client
    - libguestfs-tools
    - virt-manager
    - virt-install
    - scap-security-guide
    - openscap
    - scap-workbench
    - google-chrome-stable
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - NetworkManager-l2tp
    - NetworkManager-l2tp-gnome
    - wget
    - vim
    - PyYAML
    - atom
    - cockpit
    - cockpit-pcp
    - tigervnc
    - python-pyghmi
    - gnome-tweak-tool
    - vlc
    - libselinux-python
    - mediawriter
    - virt-viewer
    - ipmitool
    - krb5-workstation
    - asciidoctor
#    - python-ovirt-engine-sdk4 #install with pip. Not in a repo available to Fedora
  become: yes
  tags: packages

- name: Install Atom's File Icons
  command: /usr/bin/apm install file-icons
  become: yes
  tags: packages

- name: Install Atom's Beautify
  command: apm install atom-beautify
  become: yes
  tags: packages

- name: Install Atom's ansible-vault
  command: apm install ansible-vault
  become: yes
  tags: packages

- name: Install Atom's ansible-vault
  command: apm install minimap
  become: yes
  tags: packages

- name: Make cockpit autostart
  command: systemctl enable cockpit.socket
  become: yes
  tags: packages

- name: Add oVirt.image-template
  command: ansible-galaxy install ovirt.image-template
  become: yes
  tags: packages
