---
- name: Update libvirtd.conf (needed for Satellite to use LibVirt as a Compute Resource)
  template:
    src: "../templates/libvirtd.conf.j2"
    dest: /etc/libvirt/libvirtd.conf
    mode: 0644
    backup: yes
  notify: restart libvirtd
  tags: libvirtd

- name: Ensure libvirtd daemon is set to listen for connections (needed for Satellite to use LibVirt as Compute Resource)
  template:
    src: "../templates/libvirtd.j2"
    dest: /etc/sysconfig/libvirtd
    mode: 0644
    backup: yes
  notify: restart libvirtd
  tags: libvirtd

- name: Make {{ libvirt_storage_pool_name }} directory
  file:
    path: /home/{{ laptop_local_user }}/{{ libvirt_storage_pool_name }}
    state: directory
    mode: 0775
  tags: libvirtd

- name: Make Original directory
  file:
    path: /home/{{ laptop_local_user }}/{{ libvirt_storage_pool_name }}/Original
    state: directory
    mode: 0775
  tags: libvirtd

- name: Create {{ libvirt_storage_pool_name }} Storage Pool from Template
  template:
    src: "../templates/custom-storage-pool.xml.j2"
    dest: /etc/libvirt/storage/{{ libvirt_storage_pool_name }}.xml
    mode: 0644
  tags: libvirtd

- name: Define LibVirt Storage Pool {{ libvirt_storage_pool_name }}
  command: virsh pool-define /etc/libvirt/storage/{{ libvirt_storage_pool_name }}.xml
  tags: libvirtd

- name: Start LibVirt Storage Pool {{ libvirt_storage_pool_name }}
  command: virsh pool-start {{ libvirt_storage_pool_name }}
  tags: libvirtd

- name: Set {{ libvirt_storage_pool_name }} Storage Pool to autostart
  command: virsh pool-autostart {{ libvirt_storage_pool_name }}
  tags: libvirtd
