---
- name: Start and Enable firewalld
  systemd: name=firewalld state=started enabled=yes
  become: yes
  tags: firewall

- name: Configure firewalld
  firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: yes
    state: enabled
    zone: FedoraWorkstation
  with_items: "{{ laptop_ports }}"
  become: yes
#  ignore_errors: yes #reference for https://github.com/ansible/ansible/issues/38161
  tags: firewall
